language: php
sudo: false

jobs:
    fast_finish: true
    include:
        - php: 7.3
        - php: 7.4
        - php: nightly
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer
        - $HOME/.phive

before_install:
    - composer self-update
    - travis_retry wget https://phar.io/releases/phive.phar
    - travis_retry wget https://phar.io/releases/phive.phar.asc
    - travis_retry gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
    - gpg --verify phive.phar.asc phive.phar

install:
    - composer install
    - travis_retry php phive.phar install --trust-gpg-keys 4AA394086372C20A,E82B2FB314E9906E

script:
    - make build
